function plot_every_figure(fignumber)


    
    switch fignumber
        case 1
            fig1;%checked
        case 2
            fig2;
        case 3
            fig3;


        case 4
            fig4;
        case 5 
            fig5;
        case 6
            fig6;
        case 6.5
            fig6b;
        case 7
            fig7;%3D
        case 7.5
            fig7b;
        case 8
            fig8;
        case 9
            fig9;
        case 10
            fig10;
        case 11
            fig11;
        case 31
            figS1;
        case 32
            figS2S3;
        case 33
            figS4;
        case 34
            figS5;
        case 35
            figS6;
        case 36
            figS8S9;
        case 37
            figS10S11;
        case 38
            figS12S13;
        case 39
            figS14;
    end

 
%         case 4
%             fig_24110603test;




%         case 14
%             fig_24110603losscurve;
%         
%         case 16 
%             fig_24121602optm;%2D
%         case 17
%             fig_corrmap_4D;
% 
%         case 19
%             fig_3Dlosscurve_10kdata;
%         case 20
%             table_3DNNfeature;
%         case 21
%             dataTable3D_test_10kdata;
%         case 22
%             dataTable3D_optm_10kdata;
%         case 23
%             fig_3Dinfer_meanR2;
%         case 24
%             fig_3Dinfer_paraR2;
% 
%         case 25
%             fig_2Dinfer_meanR2;
%         case 26
%             fig_2Dinfer_paraR2;
% % 
% 
%     end



end

function fig1
    fs = 40; ms = 20;
    % Load data: generated by GPR_generate_insulin_data.ipynb
    d = load('prepare_fig1_confidence_data.mat');
    x = d.test_x;
    low = d.lower_rescaledback;
    up  = d.upper_rescaledback;
    y   = d.subjins25;
    
    % Mean curve
    meanval = [358.5663,192.7986,152.8831,93.8441,61.7299,21.0156,11.5079,8.3109,6.8725,...
               6.3893,5.4048,5.6017,4.9837,5.5729,6.0399,5.7293];
    % Main plot
    figure;
    ax1 = subplot(1,1,1);
    fill(ax1,[x,fliplr(x)],[low,fliplr(up)],'r'); hold(ax1,'on');%,'FaceAlpha',.5
    plot(ax1,x,y(~ismember(1:size(y,1),[3,11,18,25]),:),'k.','MarkerSize',ms);
    plot(ax1,x,meanval,'b-','LineWidth',2);
    xlabel(ax1,'Time'); ylabel(ax1,'Insulin level');
    grid(ax1,'on'); axis(ax1,[20 185 0 550]); set(ax1,'FontSize',fs);
    
    % Zoomed inset
    ax2 = axes('Position',[.25 .35 .65 .45]);
    fill(ax2,[x,fliplr(x)],[low,fliplr(up)],'r'); hold(ax2,'on');%,'FaceAlpha',.5
    idx = x > 40;
    plot(ax2,x(idx),y(~ismember(1:size(y,1),[3,11,18,25]),idx),'k.','MarkerSize',ms);
    plot(ax2,x,meanval,'b-','LineWidth',2);
    grid(ax2,'on'); axis(ax2,[40 185 0 20]); set(ax2,'FontSize',fs);
    set(gcf,'PaperPositionMode','auto');
    print(gcf,'-dpng','-r600','Figure 1.png'); 
%     print(gcf,'-depsc2','-r600','All figures/Figure 1.eps');
end




function fig2
    gludata = importdata('25FSIGT_Glu.csv');
    FFAdata = importdata('25FSIGT_FFA.csv');    
    GIF0 = importdata('25FSIGT_GIF0.csv');

    all6para=importdata('optimizedparameters_3Dmodel.csv');
    alloptmpara=zeros(25,11); 
    alloptmpara(:,1:6)=all6para;
    alloptmpara(:,7:9)=GIF0;
    alloptmpara(:,10)=gludata(:,1);
    alloptmpara(:,11)=FFAdata(:,1);

    alloptmpara_used=[alloptmpara(:,1:7),alloptmpara(:,9:11)];
    inused=importdata('prepare_fig2_parameterset3DdecF_mvlgnmDirect_first10kdata_of3930694.csv'); 
    figure; tiledlayout(3, 4);fs=30;
    columnNames = {'$S_I$','$C_X$','$S_G$','$X_2$','$C_F$','$L_2$','$G_b$','$F_b$','Initial condition of $G$','Initial condition of $F$'};
    
    tileOrder = [1, 2,5,6,9,10,3,7,4,8];
    IDexcludeOutliners=[1:2,4:10,12:17,19:24];

    num_params=10;
    for p = 1:num_params
        nexttile(tileOrder(p));
        histogram(inused(:,p) , 80, 'Normalization', 'probability','FaceColor','b');hold on;%.^(powers(p)
        histogram(alloptmpara_used(IDexcludeOutliners,p),20,'Normalization','probability','FaceColor','r');hold on
        xlim([min(alloptmpara_used(IDexcludeOutliners,p)) ,max(alloptmpara_used(IDexcludeOutliners,p)) ]);
        title(sprintf(columnNames{p}),'Interpreter','latex');
        set(gca, 'FontSize', fs);
    end
    set(gcf,'PaperPositionMode','auto');
%     print(gcf,'-dpng','-r600','Figure 2.png'); 
    print(gcf,'-depsc2','-r600','All figures/Figure 2.eps');
end


function fig3
    Para2= importdata('prepare_fig3_optmpara_2Dmodel.csv');
    in=importdata('prepare_fig3_parameterset2D_mvlgnmDirectparaphybd_first10kdata_of2877269.csv');
    figure; tiledlayout(2, 3);fs=40;
    columnNames = {'$S_{GF}$','$P_{X \\alpha}$',  '$S_{Fb}$', '$P_X$', '$F_b$'};
    IDexcludeOutliners=[1:2,5:10,12:17,19:24];
    parashow=Para2(IDexcludeOutliners,:);
    num_params=5;
    for p = 1:num_params
        nexttile;%(tileOrder(p));
        histogram(in(:,p) , 100, 'Normalization', 'probability','FaceColor','b');hold on;%.^(powers(p)
        histogram(parashow(:,p),20,'Normalization','probability','FaceColor','r');hold on
        xlim([min(parashow(:,p)) ,max(parashow(:,p)) ]);
        title(sprintf(columnNames{p},'Interpreter','latex'),'Interpreter','latex');
        set(gca, 'FontSize', fs);
    end
    set(gcf,'PaperPositionMode','auto');
%     print(gcf,'-dpng','-r600','Figure 3.png'); 
    print(gcf,'-depsc2','-r600','All figures/Figure 3.eps');
end


function fig4
    gludata = importdata('25FSIGT_Glu.csv');FFAdata = importdata('25FSIGT_FFA.csv');    
    chosensubjs=[1:2,4:10,12:17,19:24];
    simudata=importdata('prepare_fig4_3DdecF_mvlgnmDirect_first10kdata_of3930694.csv'); 
    optmG=importdata('GFX3D25_optmG.csv');optmF=importdata('GFX3D25_optmF.csv');
    simuG=simudata(:,2:4:62);simuF=simudata(:,4:4:64);
    experiG=gludata( chosensubjs,:);experiF=FFAdata( chosensubjs,:);
    Errorbars_GFtraj_3D(experiG,experiF,optmG( chosensubjs,:),optmF( chosensubjs,:),simuG,simuF)
end

function fig5
    FFAdata = importdata('25FSIGT_FFA_alltime.csv');    
    chosensubjs=[1:2,4:10,12:17,19:24];
    optmF2D=importdata('FX2D25LIP_optmF_241214.csv');
    simudata=importdata('Out250130FX2D25_mvlognmdirectparaphybd_2877269_first10k.csv');
    simuF=simudata(:,4:4:112);
    experiF=FFAdata( chosensubjs,:);
    Errorbars_GFtraj_2D(experiF,optmF2D( chosensubjs,:),simuF);
end


function Errorbars_GFtraj_3D(experiG,experiF,optmG,optmF,simuG,simuF)
%     t_vec22=[22,24,25,27,30,40,50,60,70,80,90,100,120,140,160,180] ;
    t_vec22=[22, 23, 24, 25, 27, 30, 40, 50, 60, 70, 80, 90, 100, 120, 150, 180];
    figure;fs=30;ms=10;lw1=30;lw2=20;lw3=10;
    tiledlayout(1,2);
    nexttile;
    errorbar(t_vec22, mean(experiG,1), std(experiG,0,1), 'o-','color','r','linewidth',lw1);hold on;
    errorbar(t_vec22, mean(optmG,1) , std(optmG,0,1), 'o-','color','k','linewidth',lw2);hold on;
    errorbar(t_vec22, mean(simuG(:,:),1) , std(simuG(:,:),0,1), 'o-','color','b','linewidth',lw3);hold on;
    xlim([20 180]);ylim([50 190]);
    set(gca,'FontSize',fs);
    nexttile;
    errorbar(t_vec22, mean(experiF,1), std(experiF,0,1), 'o-','color','r','linewidth',lw1);hold on;
    errorbar(t_vec22, mean(optmF,1) , std(optmF,0,1), 'o-','color','k','linewidth',lw2);hold on;
    errorbar(t_vec22, mean(simuF(:,:),1) , std(simuF(:,:),0,1), 'o-','color','b','linewidth',lw3);hold on;
    xlim([20 180]);ylim([0 650]);
    set(gca,'FontSize',fs);
        set(gcf,'PaperPositionMode','auto');
%     print(gcf,'-dpng','-r600','Figure 4.png'); 
    print(gcf,'-depsc2','-r600','All figures/Figure 4.eps');
end


function Errorbars_GFtraj_2D(experiF,optmF,simuF)
    tbefore22=[0, 2, 3, 4, 5, 6, 8, 10, 12, 14, 16, 19, 22];
    %     t_vec22=[22,24,25,27,30,40,50,60,70,80,90,100,120,140,160,180] ;
    t_vec22=[22, 23, 24, 25, 27, 30, 40, 50, 60, 70, 80, 90, 100, 120, 150, 180];
    t_vec0to180=[tbefore22,t_vec22(2:end)];
    figure;fs=30;ms=30;lw1=30;lw2=20;lw3=10;
    errorbar(t_vec0to180, mean(experiF,1), std(experiF,0,1), 'o-','color','r','linewidth',lw1);hold on;
    errorbar(t_vec0to180, mean(optmF,1) , std(optmF,0,1), 'o-','color','k','linewidth',lw2);hold on;
    errorbar(t_vec0to180, mean(simuF(:,:),1) , std(simuF(:,:),0,1), 'o-','color','b','linewidth',lw3);hold on;
    xlim([0 185]); ylim([0 650]);
    set(gca,'FontSize',fs);
    ax = gca;
    ax.YAxis.TickLabelGapOffset = 15;   % move labels 5 points to the left
    set(gcf,'PaperPositionMode','auto');
%     print(gcf,'-dpng','-r600','Figure 5.png'); 
print(gcf,'-depsc2','-r600','All figures/Figure 5.eps');
 end
 function fig6
     Ntrainshow = 5000;
    parainfertrain = importdata('inferencefromnetwork/paragiventrain_Mvlognormaldirect_25011504.csv');
    paratrain      = importdata('inferencefromnetwork/parainfertrain_Mvlognormaldirect_25011504.csv');
    fs    = 36;    % bumped up toward 40
    ms    = 30;
    msblue= 18;
    lw    = 4;
    columnNames = {'$S_I$','$C_X$','$S_G$','$X_2$','$C_F$','$L_2$','$G_b$','$F_b$','$G_{22}$','$F_{22}$'};
    
    figure;
    tiledlayout(2,4,'Padding','compact','TileSpacing','compact');  % make it tight
    
    for k = 1:8
        y_true = paratrain(:,k);
        y_pred = parainfertrain(:,k);
        X = [ones(length(y_pred),1), y_pred];
        [~,~,~,~,stats] = regress(y_true, X);
        R2_train = stats(1);
    
        nexttile; hold on;
            plot(paratrain(1:Ntrainshow,k), parainfertrain(1:Ntrainshow,k), 'b.','MarkerSize', msblue);
            min_val = min(paratrain(1:Ntrainshow,k));
            max_val = max(paratrain(1:Ntrainshow,k));
            plot([min_val, max_val], [min_val, max_val], 'k--','LineWidth', lw);
            xlim([min_val max_val]);
            ylim([min_val max_val]);
    
            title(columnNames{k}, 'FontSize', fs, 'Interpreter', 'latex');
            text(...
              min_val + 0.05*(max_val-min_val), ...
              max_val - 0.05*(max_val-min_val), ...
              sprintf('$R^2$ = %.3f', R2_train), ...
              'FontSize', fs-5, 'Interpreter', 'latex', ...
              'HorizontalAlignment','left','VerticalAlignment','top', ...
              'EdgeColor','k','BackgroundColor','w','Margin',5);
    
            box 'on'
            if k==1
                ax = gca;
                ax.XAxis.Exponent = 0;      % disable 10^−3 exponent
                xtickformat('%.3f');        % show 4 decimal places, e.g. 0.0020
            end
            if k>=5
                xlabel('True',    'FontSize', fs);
            end
            if mod(k,4)==1
                ylabel('Inferred','FontSize', fs);
            end
            set(gca,'FontSize',fs);
        hold off;
    end

    set(gcf,'PaperPositionMode','auto');
%     print(gcf,'-dpng','-r600','Figure 6.png');
    print(gcf,'-depsc2','-r600','All figures/Figure 6.eps');
 end


 function fig6b


   Ntrainshow=5000;
    paratrain=importdata('inferencefromnetwork/paratrain_24121602.csv');
    parainfertrain=importdata('inferencefromnetwork/parainfertrain_24121602.csv');
   Nsubset=100;
    fs=40;ms=30;msblue=18;lw=4;
    columnNames={'$S_{GF}$', '$S_{Fb}$', '$P_{X\alpha}$', '$P_X$', '$F_b$'};
     figure;tiledlayout(2,3);
        for k = 1:5
            y_true=paratrain(1:Nsubset,k);
            y_pred=parainfertrain(1:Nsubset,k);
            X = [ones(length(y_pred), 1), y_pred];  % Add a column of ones for the intercept
            [b, ~, ~, ~, stats] = regress(y_true, X);  % Perform linear regression
            p_train = stats(3);  % p-value for the regression model

            R2_train = stats(1);

            nexttile;hold on;
             plot(paratrain(1:Ntrainshow,k),parainfertrain(1:Ntrainshow,k),'b.','markersize',msblue);hold on;
            min_val = min(paratrain(1:Ntrainshow, k));
            max_val = max(paratrain(1:Ntrainshow, k));
            plot([min_val, max_val], [min_val, max_val], 'k--','linewidth',lw);
            xlim([min_val max_val]);
            ylim([min_val max_val]);

            title(sprintf('%s',columnNames{k}),'fontsize',fs,'Interpreter','latex');box 'on';  %.3f
      
            text(max_val - 0.05 * (max_val - min_val), min_val + 0.05 * (max_val - min_val), ...
                    sprintf('$R^2$ = %.4f', R2_train), ...%\n $p$=%.9f%, p_train
                    'HorizontalAlignment', 'right', 'VerticalAlignment', 'bottom', ...
                    'FontSize', fs , 'Interpreter', 'latex', 'EdgeColor', 'black', ...
                    'BackgroundColor', 'white', 'Margin', 5);
                %    $R^2$ value: 
            %     title(sprintf('%s    p-value: %.3f, %.3f;\n R2-value: %.3f, %.3f',columnNames{k}, p_train,p_real,R2_train,  R2_real));box 'on';
%             if k==1  
%                 ax = gca;
%                 ax.XAxis.Exponent = 0; ax.YAxis.Exponent = 0;       % disable 10^−3 exponent
%                 xtickformat('%.3f');ytickformat('%.3f');         % show 4 decimal places, e.g. 0.0020
%             elseif k==2
%                                 ax = gca;
%                 ax.XAxis.Exponent = 0;  ax.YAxis.Exponent = 0;      % disable 10^−3 exponent
%                 xtickformat('%.4f');        % show 4 decimal places, e.g. 0.0020
%                 ytickformat('%.4f');    
%             end
                        
            if k>=3
                xlabel('True');
            end
            if mod(k,3)==1
                ylabel('Inferred');
            end
            set(gca,'fontsize',fs);
            hold off;
        end
    set(gcf,'PaperPositionMode','auto');
%     print(gcf,'-dpng','-r600','Figure 6b.png');
    print(gcf,'-depsc2','-r600','All figures/Figure 6b.eps');

 end

function fig7
Ntrainshow = 5000;

parainfertrain = importdata('inferencefromnetwork/paragiventrain_Mvlognormaldirect_25011504.csv');
paratrain      = importdata('inferencefromnetwork/parainfertrain_Mvlognormaldirect_25011504.csv');

parainfertest  = importdata('inferencefromnetwork/paragiventest_Mvlognormaldirect_25011504.csv');
paratest       = importdata('inferencefromnetwork/parainfertest_Mvlognormaldirect_25011504.csv');

gludata = importdata('25FSIGT_Glu.csv');
FFAdata = importdata('25FSIGT_FFA.csv');
GIF0    = importdata('25FSIGT_GIF0.csv');
all6para      = importdata('optimizedparameters_3Dmodel.csv');
alloptmpara   = zeros(25,11);
alloptmpara(:,1:6)   = all6para;
alloptmpara(:,7:9)   = GIF0;
alloptmpara(:,10)    = gludata(:,1);
alloptmpara(:,11)    = FFAdata(:,1);
alloptmpara_used     = [alloptmpara(:,1:7), alloptmpara(:,9:11)];

parainferoptm = importdata('inferencefromnetwork/parainferfromoptm_Mvlognormaldirect_25011504.csv');
paratrue      = alloptmpara_used(:,1:8);

fs     = 36;    % bumped up toward 40
ms     = 30;
msblue = 18;
lw     = 4;
chosensubjs = [1:2,4:10,12:17,19:24];
columnNames = {'$S_I$','$C_X$','$S_G$','$X_2$','$C_F$','$L_2$','$G_b$','$F_b$','$G_{22}$','$F_{22}$'};

figure;
tiledlayout(2,4,'Padding','compact','TileSpacing','compact');

for k = 1:8
    % --- test data fit
    y_true = paratest(:,k);
    y_pred = parainfertest(:,k);
    X = [ones(length(y_pred),1), y_pred];
    [~,~,~,~,stats] = regress(y_true, X);
    R2_test = stats(1);

    nexttile; hold on;
        plot(y_true(1:Ntrainshow), y_pred(1:Ntrainshow), 'b.','MarkerSize',msblue);
        min_val = min(y_true(1:Ntrainshow));
        max_val = max(y_true(1:Ntrainshow));
        plot([min_val,max_val], [min_val,max_val], 'k--','LineWidth',lw);

    % --- optm data overlay
        y_true = paratrue(chosensubjs,k);
        y_pred = parainferoptm(chosensubjs,k);
        plot(y_true, y_pred, 'm.','MarkerSize',ms);

        X = [ones(length(y_pred),1), y_pred];
        [~,~,~,~,stats] = regress(y_true, X);
        R2_optm = stats(1);

        xlim([min_val max_val]);
        ylim([min_val max_val]);

        title(columnNames{k}, 'FontSize', fs, 'Interpreter', 'latex');
        box on;

        % annotations
        text(...
          min_val + 0.05*(max_val-min_val), ...
          max_val - 0.05*(max_val-min_val), ...
          sprintf('Test: %.3f', R2_test), ...
          'FontSize', fs-5, 'Interpreter', 'latex', ...
          'HorizontalAlignment','left','VerticalAlignment','top', ...
          'EdgeColor','k','BackgroundColor','w','Margin',5);

        text(...
          max_val - 0.05*(max_val-min_val), ...
          min_val + 0.05*(max_val-min_val), ...
          sprintf('Optm: %.3f', R2_optm), ...
          'FontSize', fs-5, 'Interpreter', 'latex', ...
          'HorizontalAlignment','right','VerticalAlignment','bottom', ...
          'EdgeColor','k','BackgroundColor','w','Margin',5);
        if k==1  
                ax = gca;
                ax.XAxis.Exponent = 0;     % disable 10^−3 exponent
                xtickformat('%.3f');          % show 4 decimal places, e.g. 0.0020

        end
    if k>=5
        xlabel('True',     'FontSize', fs);
    end
    if mod(k,4)==1
        ylabel('Inferred', 'FontSize', fs);
    end
        set(gca,'FontSize',fs);
    hold off;
end

set(gcf,'PaperPositionMode','auto');
% print(gcf,'-dpng','-r600','Figure 7.png');
    print(gcf,'-depsc2','-r600','All figures/Figure 7.eps');

end

function fig7b   
    Ntrainshow=5000;
    paratrain=importdata('inferencefromnetwork/paratrain_24121602.csv');
    parainfertrain=importdata('inferencefromnetwork/parainfertrain_24121602.csv');
    paratest=importdata('inferencefromnetwork/paratest_24121602.csv');
    parainfertest=importdata('inferencefromnetwork/parainfertest_24121602.csv');
    paraoptm=importdata('prepare_fig3_optmpara_2Dmodel.csv');
    paratrue=paraoptm(:,1:5);
    parainferoptm=importdata('inferencefromnetwork/parainferfromoptm_Mvlognormal25_24121602.csv');
    fs=40;ms=30;msblue=18;lw=4;
    chosensubjs=[1:2,4:10,12:17,19:24];
    columnNames={'$S_{GF}$', '$S_{Fb}$', '$P_{X\alpha}$', '$P_X$', '$F_b$'};
    figure;tiledlayout(2,3);
    for k = 1:5
        y_true=paratest(:,k);
        y_pred=parainfertest(:,k);
        X = [ones(length(y_pred), 1), y_pred];  % Add a column of ones for the intercept
        [b, ~, ~, ~, stats] = regress(y_true, X);  % Perform linear regression
        p_test = stats(3);  % p-value for the regression model
        R2_test = stats(1);        
        nexttile;hold on;
        plot(paratest(1:Ntrainshow,k),parainfertest(1:Ntrainshow,k),'b.','markersize',msblue);hold on;
        min_val = min(paratest(1:Ntrainshow, k));
        max_val = max(paratest(1:Ntrainshow, k));
        plot([min_val, max_val], [min_val, max_val], 'k--','linewidth',lw);
        xlim([min_val max_val]);
        ylim([min_val max_val]);
        y_true=paratrue(chosensubjs,k);
        y_pred=parainferoptm(chosensubjs,k);
        plot(y_true,y_pred,'m.','Markersize',ms);hold on;
        
        X = [ones(length(y_pred), 1), y_pred];  % Add a column of ones for the intercept
        [b, ~, ~, ~, stats] = regress(y_true, X);  % Perform linear regression
        p_optm = stats(3);  % p-value for the regression model
        R2_optm = stats(1);
        title(sprintf('%s',columnNames{k}),'fontsize',fs,'Interpreter','latex');box 'on';   %.3f
        
        text(min_val + 0.05 * (max_val - min_val),max_val - 0.05 * (max_val - min_val),  ...
        sprintf('Test:  %.3f', R2_test), ...%,R2_optm%\nOptm: $R^2$ = %.3f
        'HorizontalAlignment', 'left', 'VerticalAlignment', 'top', ...
        'FontSize', fs , 'Interpreter', 'latex', 'EdgeColor', 'black', ...
        'BackgroundColor', 'white', 'Margin', 5);
%         

         text(max_val - 0.03 * (max_val - min_val),min_val + 0.05 * (max_val - min_val),  ...
        sprintf('Optm:  %.3f', R2_optm), ...%Test: $p$ = %.4f\n
        'HorizontalAlignment', 'right', 'VerticalAlignment', 'bottom', ...
        'FontSize', fs , 'Interpreter', 'latex', 'EdgeColor', 'black', ...
        'BackgroundColor', 'white', 'Margin', 5); 
%                      text(max_val - 0.05 * (max_val - min_val),min_val + 0.05 * (max_val - min_val),  ...
%                     sprintf('Test: $p$ = %.4f\nOptm: $p$ = %.4f', p_test,p_optm), ...
%                     'HorizontalAlignment', 'right', 'VerticalAlignment', 'bottom', ...
%                     'FontSize', fs - 5, 'Interpreter', 'latex', 'EdgeColor', 'black', ...
%                     'BackgroundColor', 'white', 'Margin', 5); 
        if k>=3
            xlabel('True'); 
        end
        if mod(k,3)==1
            ylabel('Inferred');
        end
        set(gca,'fontsize',fs);hold off;
    end
    set(gcf,'PaperPositionMode','auto');
%     print(gcf,'-dpng','-r600','Figure 7b.png'); 
    print(gcf,'-depsc2','-r600','All figures/Figure 7b.eps');
end

function fig8
    % Read the CSV file into a MATLAB table
    dataTable_1248kdata = readtable('dataTable_1248kdata_forFigureP.csv');
    % Sort dataTable_used in the order: npara -> activation -> FeatureType
    sortOrder = [ "Activation", "ntrain","FeatureType"]; % Sorting criteria
    dataTable_sorted = sortrows(dataTable_1248kdata(33:64,:), sortOrder, 'ascend');
    titles = {'Ntrain=1000','Ntrain=2000','Ntrain=4000','Ntrain=8000'};

    % Create figure
    figure;t=tiledlayout(2,4,'Padding','compact','TileSpacing','compact');
    fs = 24;lw=2;fs_label=24;fs_title=24;
    cell_color= {'r', 'g', 'b','k'};
     inset_ylim=1e-3.*[4.9 5.3;     2.9 3.5;    1.8 2.7;    0.9 1.3    ;...
                3.3 3.9;    1.95 2.4;    1.4 1.75;    0.65 0.9   ];
    for k = 1:8
        ax = nexttile(t,k);hold on;
        hold(ax, 'on'); box(ax, 'on');
        jobSubset = dataTable_sorted.JobNumber((k-1)*4 + (1:4)); % 4 jobs per subplot
        mat_valloss=zeros(4,2000);
        for i = 1:4
            jobNumber = jobSubset(i);
            filename = sprintf('train_val_losses/%d_val_losses.csv', jobNumber);     
            if exist(filename, 'file')
                val_losses = readmatrix(filename);
                mat_valloss(i,:)=val_losses';
            else
                fprintf('Skipping Job %d: File not found.\n', jobNumber);
            end
            plot(ax, 1:size(mat_valloss,2), mat_valloss(i,:), 'Color', cell_color{i}, 'LineWidth', lw);
            if k==5
                legend('No Feature Engineering','Concatenation','Reciprocals vs. time',...
                    'Mutual reciprocals', 'NumColumns', 1,'fontsize',20);    %legend('noFE','catonly','twithreci','fullreci', 'NumColumns', 2);
            end
        end
    
        xlim([0 2000]);
        set(gca,'fontsize',fs);
        if k==1
            ylabel('Validation loss with ReLU','fontsize',fs_label);
        elseif k==5
            ylabel('Validation loss with (tanh(x)+1)/2','fontsize',fs_label);
        end
        if k<=4
            title(titles{k},'fontsize',fs_title);     
        else
            xlabel('Epoch number','fontsize',fs_label);
        end
        insetPos = get(ax, 'Position');
    
        if k==1
            insetAx = axes('Position', [insetPos(1) - 0.035, insetPos(2) + 0.21, insetPos(3) * 0.7, insetPos(4) * 0.4], 'Parent', gcf);
            hold(insetAx, 'on'); box(insetAx, 'on');
        elseif k<=3
            insetAx = axes('Position', [insetPos(1) - 0.035, insetPos(2) + 0.19, insetPos(3) * 1.35, insetPos(4) * 0.5], 'Parent', gcf);
            hold(insetAx, 'on'); box(insetAx, 'on');
        elseif k==4
            insetAx = axes('Position', [insetPos(1) - 0.03, insetPos(2) + 0.19, insetPos(3) * 1.4, insetPos(4) * 0.5], 'Parent', gcf);
            hold(insetAx, 'on'); box(insetAx, 'on');
        elseif k==5
            insetAx = axes('Position', [insetPos(1) - 0.045, insetPos(2) + 0.02 , insetPos(3) * 1.3, insetPos(4) * 0.4], 'Parent', gcf);
            hold(insetAx, 'on'); box(insetAx, 'on');
        elseif k>=6
            insetAx = axes('Position', [insetPos(1) - 0.035, insetPos(2) + 0.05, insetPos(3) * 1.3, insetPos(4) * 0.7], 'Parent', gcf);
            hold(insetAx, 'on'); box(insetAx, 'on');
        end
        % Plot zoomed-in version inside the inset
        for i=1:4
            plot(insetAx, 1:size(mat_valloss,2), mat_valloss(i,:), 'Color', cell_color{i}, 'LineWidth', 1.5);
        end
        ylim(insetAx, inset_ylim(k,:)); 
        xlim(insetAx, [1500 2000]); % Focus on later epochs
        set(insetAx, 'XTick', [1500,1750,2000]);%, 'YTick', []);
        set(insetAx,'fontsize',fs);
    end
    set(gcf,'PaperPositionMode','auto');
%     print(gcf,'-dpng','-r600','Figure 8.png');    
    print(gcf,'-depsc2','-r600','All figures/Figure 7b.eps');
end

function fig9
    % Read the CSV file into a MATLAB table
    dataTable_1248kdata = readtable('dataTable_1248kdata_forFigureP.csv');
    % Sort dataTable_used in the order: npara -> activation -> FeatureType
    sortOrder = [ "Activation", "ntrain","FeatureType"]; % Sorting criteria
    dataTable_sorted = sortrows(dataTable_1248kdata(1:32,:), sortOrder, 'ascend');
    titles = {'Ntrain=1000','Ntrain=2000','Ntrain=4000','Ntrain=8000'};

    % Create figure
    figure;t=tiledlayout(2,4,'Padding','compact','TileSpacing','compact');
    fs = 24;lw=2;fs_label=24;fs_title=24;
    cell_color= {'r', 'g', 'b','k'};
    inset_ylim=1e-3.*[4.2 5.2;     2.0 4.5;    41.75 43;    0.95 1.65    ;...
                    2.7 3.8;    1.6 2.3;    1.1 1.6;    0.7 0.95   ];
     
    for k = 1:8
        ax = nexttile(t,k);hold on;
        hold(ax, 'on'); box(ax, 'on');
        jobSubset = dataTable_sorted.JobNumber((k-1)*4 + (1:4)); % 4 jobs per subplot
        mat_valloss=zeros(4,2000);
        for i = 1:4
            jobNumber = jobSubset(i);
            filename = sprintf('train_val_losses/%d_val_losses.csv', jobNumber);     
            if exist(filename, 'file')
                val_losses = readmatrix(filename);
                mat_valloss(i,:)=val_losses';
            else
                fprintf('Skipping Job %d: File not found.\n', jobNumber);
            end
            plot(ax, 1:size(mat_valloss,2), mat_valloss(i,:), 'Color', cell_color{i}, 'LineWidth', lw);
            if k==1
                legend('No Feature Engineering','Concatenation','Reciprocals vs. time',...
                    'Mutual reciprocals', 'NumColumns', 1,'fontsize',20);    %legend('noFE','catonly','twithreci','fullreci', 'NumColumns', 2);
            end
        end
    
        xlim([0 2000]);
        set(gca,'fontsize',fs);
        if k==1
            ylabel('Validation loss with ReLU','fontsize',fs_label);
        elseif k==5
            ylabel('Validation loss with (tanh(x)+1)/2','fontsize',fs_label);
        end
        if k<=4
            title(titles{k},'fontsize',fs_title);     
        else
            xlabel('Epoch number','fontsize',fs_label);
        end
        insetPos = get(ax, 'Position');
    
        if k==1
            insetAx = axes('Position', [insetPos(1) - 0.035, insetPos(2) + 0.15, insetPos(3) * 0.725, insetPos(4) * 0.25], 'Parent', gcf);
            hold(insetAx, 'on'); box(insetAx, 'on');
        elseif k<=4
            insetAx = axes('Position', [insetPos(1) - 0.035, insetPos(2) + 0.19, insetPos(3) * 1.3, insetPos(4) * 0.5], 'Parent', gcf);
            hold(insetAx, 'on'); box(insetAx, 'on');
        elseif k>=5
            insetAx = axes('Position', [insetPos(1) - 0.035, insetPos(2) + 0.05, insetPos(3) * 1.3, insetPos(4) * 0.7], 'Parent', gcf);
            hold(insetAx, 'on'); box(insetAx, 'on');
        end
        % Plot zoomed-in version inside the inset
        for i=1:4
            plot(insetAx, 1:size(mat_valloss,2), mat_valloss(i,:), 'Color', cell_color{i}, 'LineWidth', 1.5);
        end
        ylim(insetAx, inset_ylim(k,:)); 
        xlim(insetAx, [1500 2000]); % Focus on later epochs
        set(insetAx, 'XTick', [1500,1750,2000]);%, 'YTick', []);
        set(insetAx,'fontsize',fs);
    end
    set(gcf,'PaperPositionMode','auto');
%     print(gcf,'-dpng','-r600','Figure 9.png');
    print(gcf,'-depsc2','-r600','All figures/Figure 9.eps');
 end

function fig10
    % --- Load & sort tables ---
    names = ["test_3D_124810kdata", "optm_3D_124810kdata", ...
             "optm_3D_500kdata",     "test_3D_500kdata"];
    for k = 1:numel(names)
        fn = fullfile("datatables", "dataTable_" + names(k) + ".csv");
        tbl{k} = sortrows(readtable(fn), {'ntrain','Activation','FeatureType'});
    end
    tbl124 = tbl(1:2);
    tbl500 = tbl{3};
    idx500 = tbl500.ntrain==500000 & tbl500.npara==6;
    feat500 = tbl500.FeatureType(idx500);
    act500  = tbl500.Activation(idx500);
    r2500   = tbl500.Mean_R2(idx500);
    
    % --- Settings ---
    fts      = {'fta_noFE','ftb_catonlytGIF','ftc_twithreciGIF','ftd_fullreci'};
    dispname = {'No Feature Engineering','Concatenation', ...
                'Reciprocals vs. time','Mutual reciprocals'};
    colors   = struct('fta_noFE','r','ftb_catonlytGIF','g', ...
                      'ftc_twithreciGIF','b','ftd_fullreci','k');
    acts     = {'relu','tanh01'};
    titles   = {'ReLU Activation','(tanh(x)+1)/2 Activation'};
    fs=35; ms=30; lw=2; gap=488000; xb=10000;
    
    % --- Precompute minima ---
    for i=1:2
      for j=1:2
        t = tbl124{i};
        mn(i,j) = min(t.Mean_R2(strcmp(t.Activation,acts{j})));
      end
    end
    
    % --- Plot with compact layout ---
    figure;
    tiledlayout(2,2,'Padding','compact','TileSpacing','compact');
    for i=1:2                     % test vs. optimized 124k
      t = tbl124{i};
      for j=1:2                   % relu vs. tanh
        ax = nexttile; hold(ax,'on');
        for f=1:4
          ft = fts{f};
          sel = strcmp(t.Activation,acts{j}) & strcmp(t.FeatureType,ft) & t.ntrain<=10000;
          plot(t.ntrain(sel),t.Mean_R2(sel),'-','Color',colors.(ft),'LineWidth',lw);
          plot(t.ntrain(sel),t.Mean_R2(sel),'.','Color',colors.(ft),'MarkerSize',ms,'HandleVisibility','off');
        end
        
        % broken-axis indicator (unchanged)
        m = mn(i,j); margin = (1-m)/10;
        ylim([m-margin,1]);
        px1=[10800,10900]; py=[m-1.5*margin, m-0.5*margin];
        px2=px1+100;
        plot(px1,py,'k','LineWidth',5,'Clipping','off');
        plot(px2,py,'k','LineWidth',5,'Clipping','off');
        fill([px1,flip(px2)],[py,flip(py)],'w','EdgeColor','none','Clipping','off');
        set(ax,'FontSize',fs);
    
        % 500k point & connector
        for k2 = find(strcmp(act500,acts{j}))'
          ft = feat500{k2}; y500 = r2500(k2);
          idx10 = find(t.ntrain==xb & strcmp(t.Activation,acts{j}) & strcmp(t.FeatureType,ft),1);
          y10 = t.Mean_R2(idx10);
          plot(500000-gap,y500,'.','Color',colors.(ft),'MarkerSize',28);
          plot([xb,500000-gap],[y10,y500],'--','Color',colors.(ft),'LineWidth',lw,'HandleVisibility','off');
        end
    
        if i==1, title(titles{j},'FontSize',fs); end
        if i==2, xlabel('$N_{\textrm{train}}$','Interpreter','latex','FontSize',fs); end
        if j==1, ylabel('mean $R^2$','Interpreter','latex'); end
        if i==1 && j==1
          legend(dispname,'Location','south','FontSize',29);
        end
        grid on; box on;
        xticks([1000,2000,4000,8000,xb,500000-gap]);
        xticklabels({'1k','2k','4k','8k','10k','500k'});
        hold(ax,'off');
      end
    end
    
    % --- Save at 600 DPI PNG and as EPS ---
    set(gcf,'PaperPositionMode','auto');
%     print(gcf,'-dpng','-r600','Figure 10.png');
     print(gcf,'-depsc2','-r600','All figures/Figure 10.eps');

end

function fig11
    % --- Load & sort tables ---
    dataTable_test_2D_124810kdata  = sortrows( ...
        readtable('datatables/dataTable_test_2D_124810kdata.csv'), ...
        {'ntrain','Activation','FeatureType'},'ascend');
    dataTable_optm_2D_124810kdata  = sortrows( ...
        readtable('datatables/dataTable_optm_2D_124810kdata.csv'), ...
        {'ntrain','Activation','FeatureType'},'ascend');
    dataTable_test_2D_500kdata     = sortrows( ...
        readtable('datatables/dataTable_test_2D_500kdata.csv'), ...
        {'ntrain','Activation','FeatureType'},'ascend');
    dataTable_optm_2D_500kdata     = sortrows( ...
        readtable('datatables/dataTable_optm_2D_500kdata.csv'), ...
        {'ntrain','Activation','FeatureType'},'ascend');
    
    % --- Feature styles & 500k data ---
    fts             = {'fta_noFE','ftb_catonlytGIF','ftc_twithreciGIF','ftd_fullreci'};
    dispname        = {'No Feature Engineering','Concatenation','Reciprocals vs. time','Mutual reciprocals'};
    colorMap        = containers.Map(fts, {'r','g','b','k'});
    feature_500k    = dataTable_optm_2D_500kdata.FeatureType;
    activation_500k = dataTable_optm_2D_500kdata.Activation;
    meanR2_500k     = dataTable_optm_2D_500kdata.Mean_R2;
    
    % --- Plot ---
    figure;
    tiledlayout(2,2,'Padding','compact','TileSpacing','compact');
    fs = 35; ms = 30; lw = 2; break_gap = 488000; xb = 10000;

    for plotIdx = 1:2
        % select test vs optimized
        if plotIdx==1
            dataTable = dataTable_test_2D_124810kdata;
        else
            dataTable = dataTable_optm_2D_124810kdata;
        end
        ntrain    = dataTable.ntrain;
        ftType    = dataTable.FeatureType;
        act       = dataTable.Activation;
        meanR2    = dataTable.Mean_R2;
        minR2_relu= min(meanR2(strcmp(act,'relu')));
        minR2_tanh= min(meanR2(strcmp(act,'tanh01')));
        
        % --- ReLU subplot ---
        ax1 = nexttile; hold(ax1,'on');
        for f = 1:numel(fts)
            sel = strcmp(act,'relu') & strcmp(ftType,fts{f}) & ntrain<=10000;
            plot(ntrain(sel), meanR2(sel), '-', 'Color', colorMap(fts{f}), 'LineWidth', lw);
            plot(ntrain(sel), meanR2(sel), '.', 'Color', colorMap(fts{f}), 'MarkerSize', ms, 'HandleVisibility','off');
        end
        % broken-axis indicator
        m = minR2_relu; margin = (1-m)/10;
        ylim([m-margin,1]);
        px1=[10800,10900]; py=[m-1.5*margin, m-0.5*margin]; px2=px1+100;
        plot(px1,py,'k','LineWidth',5,'Clipping','off');
        plot(px2,py,'k','LineWidth',5,'Clipping','off');
        fill([px1,flip(px2)],[py,flip(py)],'w','EdgeColor','none','Clipping','off');
        set(ax1,'FontSize',fs);
        % 500k points & connectors
        idxR = strcmp(activation_500k,'relu');
        for j = find(idxR)'
            ft = feature_500k{j};
            idx10 = find(ntrain==xb & strcmp(act,'relu') & strcmp(ftType,ft),1);
            y10 = meanR2(idx10);
            y500= meanR2_500k(j);
            plot([xb,500000-break_gap],[y10,y500],'--','Color',colorMap(ft),'LineWidth',lw,'HandleVisibility','off');
            plot(500000-break_gap,y500,'.','Color',colorMap(ft),'MarkerSize',ms,'LineWidth',2);
        end
        title('ReLU Activation','FontSize',fs);
        if plotIdx==2, xlabel('$N_{\textrm{train}}$','Interpreter','latex','FontSize',fs); end
        ylabel('mean $R^2$','Interpreter','latex','FontSize',fs);
        % correct x-ticks
        xticks([1000,2000,4000,8000,10000,500000-break_gap]);
        xticklabels({'1k','2k','4k','8k','10k','500k'});
        grid on; box on; hold(ax1,'off');
        
        % --- tanh subplot ---
        ax2 = nexttile; hold(ax2,'on');
        for f = 1:numel(fts)
            sel = strcmp(act,'tanh01') & strcmp(ftType,fts{f}) & ntrain<=10000;
            plot(ntrain(sel), meanR2(sel), '-', 'Color', colorMap(fts{f}), 'LineWidth', lw);
            plot(ntrain(sel), meanR2(sel), '.', 'Color', colorMap(fts{f}), 'MarkerSize', ms, 'HandleVisibility','off');
        end
        m = minR2_tanh; margin = (1-m)/10;
        ylim([m-margin,1]);
        px1=[10800,10900]; py=[m-1.5*margin, m-0.5*margin]; px2=px1+100;
        plot(px1,py,'k','LineWidth',5,'Clipping','off');
        plot(px2,py,'k','LineWidth',5,'Clipping','off');
        fill([px1,flip(px2)],[py,flip(py)],'w','EdgeColor','none','Clipping','off');
        set(ax2,'FontSize',fs);
        idxT = strcmp(activation_500k,'tanh01');
        for j = find(idxT)'
            ft = feature_500k{j};
            idx10 = find(ntrain==xb & strcmp(act,'tanh01') & strcmp(ftType,ft),1);
            y10 = meanR2(idx10);
            y500= meanR2_500k(j);
            plot([xb,500000-break_gap],[y10,y500],'--','Color',colorMap(ft),'LineWidth',lw,'HandleVisibility','off');
            plot(500000-break_gap,y500,'.','Color',colorMap(ft),'MarkerSize',ms,'LineWidth',2);
        end
        title('(tanh(x)+1)/2 Activation','FontSize',fs);
        if plotIdx==2, xlabel('$N_{\textrm{train}}$','Interpreter','latex','FontSize',fs); end
        % legend on second subplot (first row) with vertical layout
        if plotIdx==1
            legend(dispname,'Location','southeast','FontSize',29,'NumColumns',1);
        end
        % correct x-ticks for tanh subplot
        xticks([1000,2000,4000,8000,10000,500000-break_gap]);
        xticklabels({'1k','2k','4k','8k','10k','500k'});
        grid on; box on; hold(ax2,'off');
        
        
    end
    set(gcf,'PaperPositionMode','auto');
%     print(gcf,'-dpng','-r600','Figure 11.png');

    print(gcf,'-depsc2','-r600','All figures/Figure 11.eps');
end

function figS1
    FFAdata = importdata('25FSIGT_FFA.csv');    
    t_vec22=[22,24,25,27,30,40,50,60,70,80,90,100,120,140,160,180] ;
    chosensubjs=[1:2,4:10,12:17,19:24];
    figure;
     lw=3;ms=30;fs=30;
     for k=1:25
         if k==3
             plot(t_vec22,FFAdata(k,:),'-','color',[150 75 0]./255,'linewidth',lw);hold on
            plot(t_vec22,FFAdata(k,:),'.','color',[150 75 0]./255,'MarkerSize',ms);hold on
         elseif ismember(k,chosensubjs)==1
            plot(t_vec22,FFAdata(k,:),'r-','linewidth',lw);hold on
            plot(t_vec22,FFAdata(k,:),'r.','MarkerSize',ms);hold on    
         else
            plot(t_vec22,FFAdata(k,:),'k-','linewidth',lw);hold on
            plot(t_vec22,FFAdata(k,:),'k.','MarkerSize',ms);hold on    
         end
     end
     set(gca,'fontsize',fs);
         set(gcf,'PaperPositionMode','auto');
%     print(gcf,'-dpng','-r600','Figure S1.png');
     print(gcf,'-depsc2','-r600','All figures/Figure S1.eps');
end

  function figS2S3
    gludata = importdata('25FSIGT_Glu.csv');
    FFAdata = importdata('25FSIGT_FFA.csv');     
    t_vec22=[22,24,25,27,30,40,50,60,70,80,90,100,120,140,160,180] ;
    optmG=importdata('GFX3D25_optmG.csv');
    optmF=importdata('GFX3D25_optmF.csv');
    figure;tiledlayout(5,5);lw1=5;lw2=4;ms=30;fs=30;
    
    for k=1 : 25
        nexttile;
        if ismember(k,[3,11,18,25])~=1
            plot(t_vec22,FFAdata(k,:),'r-','LineWidth',lw1);hold on;
            plot(t_vec22,FFAdata(k,:),'r.','markersize',ms);hold on;
            plot(t_vec22,optmF(k,:),'b-','LineWidth',lw2);hold on;
        %     plot(t_vec22,reconsFfromoptm(k,:),'g-');hold on;
            if k<=20
                xticks([]);
            else
                xticks([22 100 180]);
            end
            xlim([15 185]);
            minv=min(FFAdata(k,:));
            maxv=max(FFAdata(k,:));
            v1=max(floor((minv - 20) / 10) * 10,0);
            v3=ceil((maxv + 20) / 10) * 10;
            v2=(v1+v3)/2;
            yticks([v1,v2,v3]);%round(minv-20),round(0.5*(minv+maxv)),round(maxv+20)]);
            ylim([v1,v3]);
            text(0.15, 0.7, sprintf('%d', k), 'Units', 'normalized', ...
            'VerticalAlignment', 'bottom', 'HorizontalAlignment', 'right', 'FontSize', fs, 'FontWeight', 'bold');
            
        else
            xticks([]);yticks([]);
        end
        box 'on'
        set(gca,'fontsize',30);%title(sprintf('Subject %d',k),'FontSize',20);
    end
    set(gcf,'PaperPositionMode','auto');
%     print(gcf,'-dpng','-r600','Figure S3.png');
        print(gcf,'-depsc2','-r600','All figures/Figure S3.eps');
    figure;
    tiledlayout(5,5);
    for k=1 : 25
        nexttile;
        if ismember(k,[3,11,18,25])~=1
            plot(t_vec22,gludata(k,:),'r-','LineWidth',lw1);hold on;
            plot(t_vec22,gludata(k,:),'r.','markersize',ms);hold on;
            plot(t_vec22,optmG(k,:),'b-','LineWidth',lw2);hold on;
            %     plot(t_vec22,reconsFfromoptm(k,:),'g-');hold on;
            if k<=20
                xticks([]);
            else
                xticks([22 100 180]);
            end
            xlim([15 185]);
            
            if mod(k,5)~=1
                yticks([]);
            end
            ylim([50 200]);
            text(0.95, 0.65, sprintf('%d', k), 'Units', 'normalized', ...
            'VerticalAlignment', 'bottom', 'HorizontalAlignment', 'right', 'FontSize', fs, 'FontWeight', 'bold');
        else
            yticks([]);xticks([]);
        end
        box 'on'
        set(gca,'fontsize',30);%title(sprintf('Subject %d',k),'FontSize',20);
    end
        set(gcf,'PaperPositionMode','auto');
%     print(gcf,'-dpng','-r600','Figure S2.png');
        print(gcf,'-depsc2','-r600','All figures/Figure S2.eps');

end

function figS4
    ste_struct=importdata('StefanovskiSameT.csv');
    ste_mat=ste_struct.data;
    options = odeset('RelTol', 1e-12, 'AbsTol', 1e-12);
    SteDataI=zeros(25,28);SteDataG=zeros(25,28);SteDataF=zeros(25,28);
    for j=1:25
        SteDataG(j,:)=ste_mat(1+28*(j-1):28*j,3)';
        SteDataI(j,:)=ste_mat(1+28*(j-1):28*j,4)';
        SteDataF(j,:)=1000.*ste_mat(1+28*(j-1):28*j,5)';
    end
    Para2=importdata('prepare_fig3_optmpara_2Dmodel.csv');
    t_vec22=[22,24,25,27,30,40,50,60,70,80,90,100,120,140,160,180] ;
    tbefore22=[0, 2, 3, 4, 5, 6, 8, 10, 12, 14, 16, 19, 22];
    t_vec0to180=[tbefore22,t_vec22(2:end)];

    figure;tiledlayout(5,5);lw1=5;ms=30;lw2=4;fs=30;
    for k=1:25
        nexttile;
        if ismember(k,[3,11,18,25])~=1
            newins=SteDataI(k,:);newglu=SteDataG(k,:);
            glufcn= @(t) interp1( t_vec0to180,newglu, t, 'linear', 'extrap');
            insfcn= @(t) interp1( t_vec0to180,newins, t, 'linear', 'extrap');
            plot(t_vec0to180,SteDataF(k,:),'r.','Markersize',ms);hold on
            plot(t_vec0to180,SteDataF(k,:),'r-','linewidth',lw1);hold on
            params=Para2(k,1:5);
            fb=params(5);
            ib=newins(1);
            fx0=[fb,0]';
            [~,xt2]=ode45(@(t,x) rhs_FX2D_LIP(t, x, params,ib, glufcn, insfcn),t_vec0to180,fx0,options);
            plot(t_vec0to180,xt2(:,1),'-','color','b','linewidth',lw2);hold on;
            if k<=20
                xticks([]);
            else
                xticks([0 90 180]);
            end
            xlim([0 185]);
            
            minv=min(SteDataF(k,:));
            maxv=max(SteDataF(k,:));
            v1=max(floor((minv - 50) / 10) * 10,0);
            v3=ceil((maxv + 50) / 10) * 10;
            v2=(v1+v3)/2;
            yticks([v1,v2,v3]);%round(minv-20),round(0.5*(minv+maxv)),round(maxv+20)]);
            ylim([v1,v3]);

            text(0.95, 0.05, sprintf('%d', k), 'Units', 'normalized', ...
             'VerticalAlignment', 'bottom', 'HorizontalAlignment', 'right', 'FontSize', fs, 'FontWeight', 'bold');
        else
            yticks([]);xticks([]);
        end
        box 'on'
        set(gca,'fontsize',30);%title(sprintf('Subject %d',k),'FontSize',20);
    end
    set(gcf,'PaperPositionMode','auto');
%     print(gcf,'-dpng','-r600','Figure S4.png');
    print(gcf,'-depsc2','-r600','All figures/Figure S4.eps');
end

function figS5

% load your data
%     aa = importdata('In241106_GFX3D25_errbardec_2060005_first100k.csv');
aa=importdata('prepare_fig2_parameterset3DdecF_mvlgnmDirect_first10kdata_of3930694.csv');
    all6para = importdata('optimizedparameters_3Dmodel.csv');
    gludata   = importdata('25FSIGT_Glu.csv');
    FFAdata   = importdata('25FSIGT_FFA.csv');
    GIF0      = importdata('25FSIGT_GIF0.csv');
    
    % build usedaa
    alloptmpara       = zeros(25,11);
    alloptmpara(:,1:6)   = all6para;
    alloptmpara(:,7:9)   = GIF0;
    alloptmpara(:,10)    = gludata(:,1);
    alloptmpara(:,11)    = FFAdata(:,1);
    chosensubj       = [1:2,4:10,12:17,19:24];
    usedaa           = alloptmpara(chosensubj,[1:7,9:11]);
    
    % correlation matrices
    corr_matrix1 = corr(usedaa);
    corr_matrix2 = corr(aa(1:10000,1:10));
    
    % create figure with compact two‐panel layout
    figure;
    tl = tiledlayout(1,2,'TileSpacing','compact','Padding','compact');
    
    % panel 1
    ax1 = nexttile(tl);
    imagesc(corr_matrix1);
    colormap(jet);            % same colormap for both
    title('Optimized parameters','FontSize',14,'Interpreter','latex');
    xlabel('Parameters','FontSize',12,'Interpreter','latex');
    ylabel('Parameters','FontSize',12,'Interpreter','latex');
    xticks(1:10); yticks(1:10);
    labels = {'$S_I$','$C_X$','$S_G$','$X_2$','$C_F$','$L_2$','$G_b$','$F_b$','$G_{22}$','$F_{22}$'};
    xticklabels(labels); yticklabels(labels);
    set(ax1,'TickLabelInterpreter','latex','FontSize',30);
%     axis equal;
    
    % panel 2
    ax2 = nexttile(tl);
    imagesc(corr_matrix2);
    title('Generated parameter samples','FontSize',14,'Interpreter','latex');
    xlabel('Parameters','FontSize',12,'Interpreter','latex');
    ylabel('Parameters','FontSize',12,'Interpreter','latex');
    xticks(1:10); yticks(1:10);
    xticklabels(labels); yticklabels(labels);
    set(ax2,'TickLabelInterpreter','latex','FontSize',30);
%     axis equal;
    
    % shared colorbar on the right
    cb = colorbar;
    cb.Layout.Tile = 'east';
    cb.Label.String      = 'Correlation Coefficient';
    cb.Label.FontSize    = 30;
    cb.Label.Interpreter = 'latex';
        set(gcf,'PaperPositionMode','auto');
%     print(gcf,'-dpng','-r600','Figure S5.png'); 
    print(gcf,'-depsc2','-r600','All figures/Figure S5.eps');
end

 function figS6
    usedaa = importdata('prepare_fig3_optmpara_2Dmodel.csv');
    aa     = importdata('prepare_fig3_parameterset2D_mvlgnmDirectparaphybd_first10kdata_of2877269.csv');
    
    corr_matrix1 = corr(usedaa);
    corr_matrix2 = corr(aa(1:10000,:));
    
    figure;
    tl = tiledlayout(1,2,'Padding','compact','TileSpacing','compact');
    
    % First tile
    ax1 = nexttile;
    imagesc(corr_matrix1);
    colormap(jet);
    title('Optimized parameters', 'FontSize', 14, 'Interpreter', 'latex');
    xlabel('Parameters', 'FontSize', 12, 'Interpreter', 'latex');
    ylabel('Parameters', 'FontSize', 12, 'Interpreter', 'latex');
    xticks(1:10); yticks(1:10);
    xticklabels({'$S_{GF}$','$P_{X\alpha}$','$S_{Fb}$','$P_X$','$F_b$'});
    yticklabels({'$S_{GF}$','$P_{X\alpha}$','$S_{Fb}$','$P_X$','$F_b$'});
    set(ax1, 'TickLabelInterpreter', 'latex', 'FontSize', 30);
    
    % Second tile
    ax2 = nexttile;
    imagesc(corr_matrix2);
    title('Generated parameter samples', 'FontSize', 14, 'Interpreter', 'latex');
    xlabel('Parameters', 'FontSize', 12, 'Interpreter', 'latex');
    ylabel('Parameters', 'FontSize', 12, 'Interpreter', 'latex');
    xticks(1:10); yticks(1:10);
    xticklabels({'$S_{GF}$','$P_{X\alpha}$','$S_{Fb}$','$P_X$','$F_b$'});
    yticklabels({'$S_{GF}$','$P_{X\alpha}$','$S_{Fb}$','$P_X$','$F_b$'});
    set(ax2, 'TickLabelInterpreter', 'latex', 'FontSize', 30);
    
    % Shared colorbar spanning both tiles
    cb = colorbar;           % create colorbar
    cb.Layout.Tile = 'east'; % place it on the east side of the layout
    cb.Label.String       = 'Correlation Coefficient';
    cb.Label.FontSize     = 30;
    cb.Label.Interpreter  = 'latex';

    set(gcf,'PaperPositionMode','auto');
%     print(gcf,'-dpng','-r600','Figure S6.png'); 
    print(gcf,'-depsc2','-r600','All figures/Figure S6.eps');

 end

 function figS8S9

    options = odeset('RelTol',1e-12,'AbsTol',1e-12);
    FSIGTNsubj = 25;
    
    gludata           = importdata('25FSIGT_Glu.csv');
    FFAdata           = importdata('25FSIGT_FFA.csv');
    insdata_after22   = importdata('25FSIGT_Ins.csv');
    insbefore22       = importdata('Insbefore22_25FSIGT.csv');
    insdata           = [insbefore22,insdata_after22(:,2:end)];
    GIF0              = importdata('25FSIGT_GIF0.csv');
    
    tindex    = 13:28;
    t_vec22   = [22,24,25,27,30,40,50,60,70,80,90,100,120,140,160,180];
    tbefore22 = [0,2,3,4,5,6,8,10,12,14,16,19,22];
    t_vec0to180 = [tbefore22,t_vec22(2:end)];
    
    all6para       = importdata('optimizedparameters_3Dmodel.csv');
    alloptmpara    = zeros(25,11);
    alloptmpara(:,1:6) = all6para;
    alloptmpara(:,7:9) = GIF0;
    alloptmpara(:,10)  = gludata(:,1);
    alloptmpara(:,11)  = FFAdata(:,1);
    
    ste_struct = importdata('StefanovskiSameT.csv');
    ste_mat    = ste_struct.data;
    experiGall = reshape(ste_mat(:,3),28,25)';
    experiIall = reshape(ste_mat(:,4),28,25)';
    experiFall = 1000*reshape(ste_mat(:,5),28,25)';
    
    experiG = experiGall(:,tindex);
    experiI = experiIall(:,tindex);
    experiF = experiFall(:,tindex);
    
    usedsubj = [1:2,4:10,12:17,19:24];
    optmG    = importdata('GFX3D25_optmG.csv');
    optmF    = importdata('GFX3D25_optmF.csv');
    
    reconsGfromoptm = zeros(FSIGTNsubj,16);
    reconsFfromoptm = zeros(FSIGTNsubj,16);
    
    paraoptm_noIb = alloptmpara(:,[1:7,9:11]);
    Jobnumber     = 25011504;
    
    parainferfromoptm = importdata(sprintf('inferencefromnetwork/parainferfromoptm_Mvlognormaldirect_%d.csv',Jobnumber));
    
    for K = 1:25
        parainfer = parainferfromoptm;
        newinsall  = insdata(K,:);
        insfcn0    = @(t) interp1(t_vec0to180,newinsall,t,'linear','extrap');
        ib         = newinsall(1);
        cx         = parainfer(K,2);
        rhs_x      = @(t,x) cx*(max(insfcn0(t)-ib,0)-x);
        [~,xfwd]   = ode45(rhs_x,[0 22],0,options);
        xt22       = xfwd(end);
    
        if size(parainfer,2)==6
            params = [parainfer(K,1:6),0,paraoptm_noIb(K,7),ib,paraoptm_noIb(K,8)];
            gfx22   = [paraoptm_noIb(K,[9,10]),xt22]';
        elseif size(parainfer,2)==8
            params = [parainfer(K,1:6),0,parainfer(K,7),ib,parainfer(K,8)];
            gfx22   = [paraoptm_noIb(K,[9,10]),xt22]';
        else
            params = [parainfer(K,1:6),0,parainfer(K,7),ib,parainfer(K,8)];
            gfx22   = [parainfer(K,[9,10]),xt22]';
        end
    
        newins22 = insdata(K,tindex);
        insfcn22 = @(t) interp1(t_vec22,newins22,t,'linear','extrap');
        [~,xt_infer] = ode45(@(t,x) rhs_GFX_noI2(t,x,params,insfcn22),t_vec22,gfx22,options);
    
        reconsGfromoptm(K,:) = xt_infer(:,1)';
        reconsFfromoptm(K,:) = xt_infer(:,2)';
    end
    
    figure;%%% Plot Fig S8
    lw = 5; fs = 20;
    tiledlayout(5,5);
    for k = 1:25
        ax = nexttile; hold(ax,'on');
        if ismember(k,usedsubj)
            plot(t_vec22,optmG(k,:),'-','color','b','LineWidth',2*lw);
            plot(t_vec22,reconsGfromoptm(k,:),'color','g','LineWidth',lw);
        else
            yticks([]);
        end
        xticks([]); box on; set(gca,'FontSize',fs);
        text(0.95,0.05,sprintf('%d',k),'Units','normalized', ...
             'VerticalAlignment','bottom','HorizontalAlignment','right', ...
             'FontSize',fs,'FontWeight','bold');
    end
    set(gcf,'PaperPositionMode','auto');
%     print(gcf,'-dpng','-r600','Figure S8.png');
    print(gcf,'-depsc2','-r600','All figures/Figure S8.eps');


    figure;%%% Plot Fig S9
    tiledlayout(5,5);
    for k = 1:25
        ax = nexttile; hold(ax,'on');
        if ismember(k,usedsubj)
            plot(t_vec22,optmF(k,:),'-','color','b','LineWidth',2*lw);
            plot(t_vec22,reconsFfromoptm(k,:),'color','g','LineWidth',lw);
        else
            yticks([]);
        end
        xticks([]); box on; set(gca,'FontSize',fs);
        text(0.95,0.05,sprintf('%d',k),'Units','normalized', ...
             'VerticalAlignment','bottom','HorizontalAlignment','right', ...
             'FontSize',fs,'FontWeight','bold');
    end
    set(gcf,'PaperPositionMode','auto');
%     print(gcf,'-dpng','-r600','Figure S9.png');
    print(gcf,'-depsc2','-r600','All figures/Figure S9.eps');
end

function figS10S11
    % --- Load & sort tables ---
    dataTable_test_3D_124810kdata = sortrows( ...
        readtable('datatables/dataTable_test_3D_124810kdata.csv'), ...
        {'ntrain','Activation','FeatureType'},'ascend');
    dataTable_optm_3D_124810kdata = sortrows( ...
        readtable('datatables/dataTable_optm_3D_124810kdata.csv'), ...
        {'ntrain','Activation','FeatureType'},'ascend');
    dataTable_test_3D_500kdata = readtable('datatables/dataTable_test_3D_500kdata.csv');
    dataTable_optm_3D_500kdata = readtable('datatables/dataTable_optm_3D_500kdata.csv');
    
    % --- Extract 500k tanh01 only, npara==6 ---
    idx_500k_test = dataTable_test_3D_500kdata.ntrain==500000 & ...
                    dataTable_test_3D_500kdata.npara==6 & ...
                    strcmp(dataTable_test_3D_500kdata.Activation,'tanh01');
    idx_500k_optm = dataTable_optm_3D_500kdata.ntrain==500000 & ...
                    dataTable_optm_3D_500kdata.npara==6 & ...
                    strcmp(dataTable_optm_3D_500kdata.Activation,'tanh01');
    feature_500k_test = dataTable_test_3D_500kdata.FeatureType(idx_500k_test);
    feature_500k_optm = dataTable_optm_3D_500kdata.FeatureType(idx_500k_optm);
    
    % --- R² column names & titles ---
    R2_params_test = {'R2_SI','R2_CX','R2_SG','R2_X2','R2_CF','R2_L2'};
    R2_params_optm = {'R2true_SI','R2true_CX','R2true_SG','R2true_X2','R2true_CF','R2true_L2'};
    clean_titles   = {'$S_I$','$C_X$','$S_G$','$X_2$','$C_F$','$L_2$'};
    
    % --- Feature styles ---
    fts      = {'fta_noFE','ftb_catonlytGIF','ftc_twithreciGIF','ftd_fullreci'};
    dispname = {'No Feature Engineering','Concatenation', ...
                'Reciprocals vs. time','Mutual reciprocals'};
    colorMap = containers.Map(fts, {'r','g','b','k'});
    
    % --- Loop over test vs. optimized ---
    for figIdx = 1:2
        if figIdx==1
            dataTable   = dataTable_test_3D_124810kdata;
            dataTable500= dataTable_test_3D_500kdata;
            idx500      = idx_500k_test;
            feat500     = feature_500k_test;
            R2_params   = R2_params_test;
            fig_title   = 'Testing Data (tanh)';
        else
            dataTable   = dataTable_optm_3D_124810kdata;
            dataTable500= dataTable_optm_3D_500kdata;
            idx500      = idx_500k_optm;
            feat500     = feature_500k_optm;
            R2_params   = R2_params_optm;
            fig_title   = 'Optimized Data (tanh)';
        end
    
        % --- Figure & layout ---
        figure;
        tiledlayout(2,3,'Padding','compact','TileSpacing','compact');
        fs = 25; ms = 30; lw = 2; break_gap = 488000; xb = 10000;
        ntrain     = dataTable.ntrain;
        featureType= dataTable.FeatureType;
        activation = dataTable.Activation;
    
        % --- Six parameters ---
        for p = 1:6
            ax = nexttile; hold(ax,'on');
            meanR2_p = dataTable.(R2_params{p});
            m = min(meanR2_p(strcmp(activation,'tanh01')));
            % plot curves ≤10k
            for f = 1:numel(fts)
                ft = fts{f};
                sel = strcmp(activation,'tanh01') & strcmp(featureType,ft) & ntrain<=10000;
                plot(ntrain(sel), meanR2_p(sel), '-', 'Color', colorMap(ft), 'LineWidth', lw);
                plot(ntrain(sel), meanR2_p(sel), '.', 'Color', colorMap(ft), 'MarkerSize', ms, 'HandleVisibility','off');
            end
            % broken axis
            margin = (1-m)/10;
            ylim([m-margin,1]);
            px1=[10800,10900]; py=[m-1.5*margin, m-0.5*margin];
            px2=px1+100;
            plot(px1,py,'k','LineWidth',5,'Clipping','off');
            plot(px2,py,'k','LineWidth',5,'Clipping','off');
            fill([px1,flip(px2)],[py,flip(py)],'w','EdgeColor','none','Clipping','off');
            set(ax,'FontSize',fs);
    
            % 500k points + connectors
            R2_500k = dataTable500.(R2_params{p})(idx500);
            for j = 1:numel(R2_500k)
                ft = feat500{j};
                idx10 = find(ntrain==xb & strcmp(activation,'tanh01') & strcmp(featureType,ft),1);
                y10 = meanR2_p(idx10);
                y500= R2_500k(j);
                plot([xb,500000-break_gap],[y10,y500],'--','Color',colorMap(ft),'LineWidth',lw,'HandleVisibility','off');
                plot(500000-break_gap, y500, '.', 'Color', colorMap(ft), 'MarkerSize', ms, 'LineWidth', 2);
            end
    
            % labels & limits
            title(clean_titles{p},'Interpreter','latex','FontSize',fs);
            if p>=4, xlabel('$N_{\textrm{train}}$','Interpreter','latex','FontSize',fs); end
            if ismember(p,[1,4]), ylabel('$R^2$','Interpreter','latex','FontSize',fs); end
            xticks([1000,2000,4000,8000,10000,500000-break_gap]);
            xticklabels({'1k','2k','4k','8k','10k','500k'});
            grid on; box on;
            hold(ax,'off');
            legendfontsize=[18,25];
            % legend on first subplot only
            if p==1
                legend(dispname,'Location','south','FontSize',legendfontsize(figIdx),'NumColumns',1);
            end
        end
        set(gcf,'PaperPositionMode','auto');
        if figIdx==1
%             print(gcf,'-dpng','-r600','Figure S10.png');
            print(gcf,'-depsc2','-r600','All figures/Figure S10.eps');
        elseif figIdx==2
%             print(gcf,'-dpng','-r600','Figure S11.png');
            print(gcf,'-depsc2','-r600','All figures/Figure S11.eps');
        end
    end
    
     

end

function figS12S13

    % --- Load & sort tables ---
tbl124_test = sortrows( ...
    readtable('datatables/dataTable_test_2D_124810kdata.csv'), ...
    {'ntrain','Activation','FeatureType'}, 'ascend');
tbl124_opt  = sortrows( ...
    readtable('datatables/dataTable_optm_2D_124810kdata.csv'), ...
    {'ntrain','Activation','FeatureType'}, 'ascend');
tbl500_test = sortrows( ...
    readtable('datatables/dataTable_test_2D_500kdata.csv'), ...
    {'ntrain','Activation','FeatureType'}, 'ascend');
tbl500_opt  = sortrows( ...
    readtable('datatables/dataTable_optm_2D_500kdata.csv'), ...
    {'ntrain','Activation','FeatureType'}, 'ascend');

% --- Common settings ---
fts        = {'fta_noFE','ftb_catonlytGIF','ftc_twithreciGIF','ftd_fullreci'};
dispname   = {'No Feature Engineering','Concatenation', ...
              'Reciprocals vs. time','Mutual reciprocals'};
colorMap   = containers.Map(fts, {'r','g','b','k'});
clean_titles = {'$S_{GF}$','$P_{X\alpha}$','$S_{Fb}$','$P_X$','$F_b$'};
params124 = {'Sfal','Pxa','Sffb','PXFCR','Fb'};
params500 = {'R2_Sfal','R2_Pxa','R2_Sffb','R2_PXFCR','R2_Fb'};
break_gap = 488000;
xb        = 10000;
fs = 25; ms = 30; lw = 2;

% --- Extract 500k tanh01 indices & features ---
idx500_test = tbl500_test.ntrain==500000 & strcmp(tbl500_test.Activation,'tanh01');
idx500_opt  = tbl500_opt.ntrain==500000  & strcmp(tbl500_opt.Activation,'tanh01');
f500_test   = tbl500_test.FeatureType(idx500_test);
f500_opt    = tbl500_opt.FeatureType(idx500_opt);
r500_test   = tbl500_test.R2_Sfal(idx500_test);    % placeholder, will index per param
r500_opt    = tbl500_opt.R2_Sfal(idx500_opt);

% --- Loop over Test vs Optimized ---
for figIdx = 1:2
    if figIdx==1
        tbl124   = tbl124_test;
        tbl500   = tbl500_test;
        idx500   = idx500_test;
        f500     = f500_test;
        r500_all = tbl500_test;
        fname    = 'All figures/Figure S12.eps';
    else
        tbl124   = tbl124_opt;
        tbl500   = tbl500_opt;
        idx500   = idx500_opt;
        f500     = f500_opt;
        r500_all = tbl500_opt;
        fname    = 'All figures/Figure S13.eps';
    end

    % --- Start figure ---
    figure;
    tiledlayout(2,3,'Padding','compact','TileSpacing','compact');
    ntrain  = tbl124.ntrain;
    act     = tbl124.Activation;
    fType   = tbl124.FeatureType;

    for p = 1:5
        ax = nexttile; hold(ax,'on');
        y124 = tbl124.(params124{p});
        m   = min(y124(strcmp(act,'tanh01')));
        % plot ≤10k curves
        for f = 1:numel(fts)
            sel = strcmp(act,'tanh01') & strcmp(fType,fts{f}) & ntrain<=10000;
            plot(ntrain(sel), y124(sel), '-', 'Color', colorMap(fts{f}), 'LineWidth', lw);
            plot(ntrain(sel), y124(sel), '.', 'Color', colorMap(fts{f}), 'MarkerSize', ms, 'HandleVisibility','off');
        end
        % broken axis
        margin = (1-m)/10;
        ylim([m-margin,1]);
        px1=[10800,10900]; py=[m-1.5*margin, m-0.5*margin]; px2=px1+100;
        plot(px1,py,'k','LineWidth',5,'Clipping','off');
        plot(px2,py,'k','LineWidth',5,'Clipping','off');
        fill([px1,flip(px2)],[py,flip(py)],'w','EdgeColor','none','Clipping','off');
        set(ax,'FontSize',fs);

        % plot 500k points & connectors for this param
        y500 = r500_all.(params500{p})(idx500);
        [~, uidx] = unique(f500,'stable');
        for j = 1:numel(uidx)
            ft = f500{uidx(j)};
            yj = y500(uidx(j));
            idx10 = find(ntrain==xb & strcmp(act,'tanh01') & strcmp(fType,ft),1);
            y10   = y124(idx10);
            plot([xb,500000-break_gap],[y10,yj],'--','Color',colorMap(ft),'LineWidth',lw,'HandleVisibility','off');
            plot(500000-break_gap,yj,'.','Color',colorMap(ft),'MarkerSize',ms,'LineWidth',2);
        end

        % labels
        title(clean_titles{p},'Interpreter','latex','FontSize',fs);
        if p>=3, xlabel('$N_{\textrm{train}}$','Interpreter','latex','FontSize',fs); end
        if ismember(p,[1,4]), ylabel('$R^2$','Interpreter','latex','FontSize',fs); end
        xticks([1000,2000,4000,8000,10000,500000-break_gap]);
        xticklabels({'1k','2k','4k','8k','10k','500k'});
        grid on; box on; hold(ax,'off');

        % legend only once
        if p==1
            loc = 'south';
            if figIdx==2, loc='north'; end
            legend(dispname,'Location',loc,'Orientation','horizontal', ...
                   'FontSize',20,'NumColumns',1);
        end
    end

    % --- Save PNG ---
    set(gcf,'PaperPositionMode','auto');
%     print(gcf,'-dpng','-r600',fname);
    print(gcf,'-depsc2','-r600',fname);
end



end

function figS14   
    t_vec22=[22, 24, 25, 27, 30, 40, 50, 60, 70, 80, 90, 100, 120, 140, 160, 180];
    FFAdata = importdata('25FSIGT_FFA.csv');denoiseFFA=importdata('FCdenoised_FFA.csv');
    figure;tiledlayout(5,5);ms=40;lw1=5;lw2=4;fs=30;
        for k=1:25
            nexttile;
            if ismember(k,[3,11,18,25])~=1
                plot(t_vec22,FFAdata(k,:),'r.','MarkerSize',ms);hold on;
                plot(t_vec22,FFAdata(k,:),'r-','LineWidth',lw1);hold on;
                plot(t_vec22,denoiseFFA(k,:),'k-','LineWidth',lw2);hold on;
                text(0.95, 0.05, sprintf('%d', k), 'Units', 'normalized', ...
                     'VerticalAlignment', 'bottom', 'HorizontalAlignment', 'right', 'FontSize', fs, 'FontWeight', 'bold');
                if k<=20
                    xticks([]);
                else
                    xticks([22 100 180]);
                end
 
                xlim([15 185]);
                minv=min(FFAdata(k,:));
                maxv=max(FFAdata(k,:));
                v1=max(floor((minv - 20) / 10) * 10,0);
                v3=ceil((maxv + 20) / 10) * 10;
                v2=(v1+v3)/2;
                yticks([v1,v2,v3]);
                ylim([v1,v3]);
            else
                xticks([]);
                yticks([]);
            end
            box 'on'
            set(gca,'FontSize',fs);
        end
    set(gcf,'PaperPositionMode','auto');
%     print(gcf,'-dpng','-r600','All figures/Figure S14.png');
    print(gcf,'-depsc2','-r600','All figures/Figure S14.eps');
 end





 